require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("bootstrap/dist/js/bootstrap")
require("../stylesheets/application.scss")
require('jquery')
require("movie_search.js")